title: Alex Eberle # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  GIS Analyst & Environmental Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/alex-eberle">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-151570556-2 # your Google Analytics tracking ID here
