<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-151570556-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-151570556-1');
</script>

title: Alex Eberle # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  GIS Analyst & Environmental Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/alex-eberle">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-151570556-1 # your Google Analytics tracking ID here
